/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as EventRouteImport } from './routes/event'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminChallengeRouteImport } from './routes/admin.challenge'
import { Route as AdminEventRouteImport } from './routes/admin.event'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminHealthTalkRouteImport } from './routes/admin.health-talk'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPembekalanRouteImport } from './routes/admin.pembekalan'
import { Route as AdminPesertaRouteImport } from './routes/admin.peserta'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRewardRouteImport } from './routes/admin.reward'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as HealthTalkIndexRouteImport } from './routes/health-talk.index'
import { Route as HealthTalkIdRouteImport } from './routes/health-talk.$id'
import { Route as PembekalanIndexRouteImport } from './routes/pembekalan.index'
import { Route as PembekalanIdRouteImport } from './routes/pembekalan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventRoute = AdminEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthTalkRoute = AdminHealthTalkRouteImport.update({
  id: '/health-talk',
  path: '/health-talk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPembekalanRoute = AdminPembekalanRouteImport.update({
  id: '/pembekalan',
  path: '/pembekalan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesertaRoute = AdminPesertaRouteImport.update({
  id: '/peserta',
  path: '/peserta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardRoute = AdminRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const HealthTalkIndexRoute = HealthTalkIndexRouteImport.update({
  id: '/health-talk/',
  path: '/health-talk/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthTalkIdRoute = HealthTalkIdRouteImport.update({
  id: '/health-talk/$id',
  path: '/health-talk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PembekalanIndexRoute = PembekalanIndexRouteImport.update({
  id: '/pembekalan/',
  path: '/pembekalan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PembekalanIdRoute = PembekalanIdRouteImport.update({
  id: '/pembekalan/$id',
  path: '/pembekalan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/akun': typeof AkunRoute
  '/beranda': typeof BerandaRoute
  '/challenge': typeof ChallengeRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reward': typeof RewardRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-talk': typeof AdminHealthTalkRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pembekalan': typeof AdminPembekalanRoute
  '/admin/peserta': typeof AdminPesertaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reward': typeof AdminRewardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/health-talk/$id': typeof HealthTalkIdRoute
  '/pembekalan/$id': typeof PembekalanIdRoute
  '/admin/': typeof AdminIndexRoute
  '/health-talk/': typeof HealthTalkIndexRoute
  '/pembekalan/': typeof PembekalanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/beranda': typeof BerandaRoute
  '/challenge': typeof ChallengeRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reward': typeof RewardRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-talk': typeof AdminHealthTalkRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pembekalan': typeof AdminPembekalanRoute
  '/admin/peserta': typeof AdminPesertaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reward': typeof AdminRewardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/health-talk/$id': typeof HealthTalkIdRoute
  '/pembekalan/$id': typeof PembekalanIdRoute
  '/admin': typeof AdminIndexRoute
  '/health-talk': typeof HealthTalkIndexRoute
  '/pembekalan': typeof PembekalanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/akun': typeof AkunRoute
  '/beranda': typeof BerandaRoute
  '/challenge': typeof ChallengeRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reward': typeof RewardRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-talk': typeof AdminHealthTalkRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pembekalan': typeof AdminPembekalanRoute
  '/admin/peserta': typeof AdminPesertaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reward': typeof AdminRewardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/health-talk/$id': typeof HealthTalkIdRoute
  '/pembekalan/$id': typeof PembekalanIdRoute
  '/admin/': typeof AdminIndexRoute
  '/health-talk/': typeof HealthTalkIndexRoute
  '/pembekalan/': typeof PembekalanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/akun'
    | '/beranda'
    | '/challenge'
    | '/event'
    | '/leaderboard'
    | '/reward'
    | '/admin/challenge'
    | '/admin/event'
    | '/admin/feedback'
    | '/admin/health-talk'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/pembekalan'
    | '/admin/peserta'
    | '/admin/reports'
    | '/admin/reward'
    | '/admin/settings'
    | '/health-talk/$id'
    | '/pembekalan/$id'
    | '/admin/'
    | '/health-talk/'
    | '/pembekalan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akun'
    | '/beranda'
    | '/challenge'
    | '/event'
    | '/leaderboard'
    | '/reward'
    | '/admin/challenge'
    | '/admin/event'
    | '/admin/feedback'
    | '/admin/health-talk'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/pembekalan'
    | '/admin/peserta'
    | '/admin/reports'
    | '/admin/reward'
    | '/admin/settings'
    | '/health-talk/$id'
    | '/pembekalan/$id'
    | '/admin'
    | '/health-talk'
    | '/pembekalan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/akun'
    | '/beranda'
    | '/challenge'
    | '/event'
    | '/leaderboard'
    | '/reward'
    | '/admin/challenge'
    | '/admin/event'
    | '/admin/feedback'
    | '/admin/health-talk'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/pembekalan'
    | '/admin/peserta'
    | '/admin/reports'
    | '/admin/reward'
    | '/admin/settings'
    | '/health-talk/$id'
    | '/pembekalan/$id'
    | '/admin/'
    | '/health-talk/'
    | '/pembekalan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AkunRoute: typeof AkunRoute
  BerandaRoute: typeof BerandaRoute
  ChallengeRoute: typeof ChallengeRoute
  EventRoute: typeof EventRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RewardRoute: typeof RewardRoute
  HealthTalkIdRoute: typeof HealthTalkIdRoute
  PembekalanIdRoute: typeof PembekalanIdRoute
  HealthTalkIndexRoute: typeof HealthTalkIndexRoute
  PembekalanIndexRoute: typeof PembekalanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenge': {
      id: '/admin/challenge'
      path: '/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event': {
      id: '/admin/event'
      path: '/event'
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health-talk': {
      id: '/admin/health-talk'
      path: '/health-talk'
      fullPath: '/admin/health-talk'
      preLoaderRoute: typeof AdminHealthTalkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pembekalan': {
      id: '/admin/pembekalan'
      path: '/pembekalan'
      fullPath: '/admin/pembekalan'
      preLoaderRoute: typeof AdminPembekalanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/peserta': {
      id: '/admin/peserta'
      path: '/peserta'
      fullPath: '/admin/peserta'
      preLoaderRoute: typeof AdminPesertaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reward': {
      id: '/admin/reward'
      path: '/reward'
      fullPath: '/admin/reward'
      preLoaderRoute: typeof AdminRewardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/health-talk/': {
      id: '/health-talk/'
      path: '/health-talk'
      fullPath: '/health-talk/'
      preLoaderRoute: typeof HealthTalkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-talk/$id': {
      id: '/health-talk/$id'
      path: '/health-talk/$id'
      fullPath: '/health-talk/$id'
      preLoaderRoute: typeof HealthTalkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembekalan/': {
      id: '/pembekalan/'
      path: '/pembekalan'
      fullPath: '/pembekalan/'
      preLoaderRoute: typeof PembekalanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembekalan/$id': {
      id: '/pembekalan/$id'
      path: '/pembekalan/$id'
      fullPath: '/pembekalan/$id'
      preLoaderRoute: typeof PembekalanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChallengeRoute: typeof AdminChallengeRoute
  AdminEventRoute: typeof AdminEventRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHealthTalkRoute: typeof AdminHealthTalkRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPembekalanRoute: typeof AdminPembekalanRoute
  AdminPesertaRoute: typeof AdminPesertaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardRoute: typeof AdminRewardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChallengeRoute: AdminChallengeRoute,
  AdminEventRoute: AdminEventRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHealthTalkRoute: AdminHealthTalkRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPembekalanRoute: AdminPembekalanRoute,
  AdminPesertaRoute: AdminPesertaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardRoute: AdminRewardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AkunRoute: AkunRoute,
  BerandaRoute: BerandaRoute,
  ChallengeRoute: ChallengeRoute,
  EventRoute: EventRoute,
  LeaderboardRoute: LeaderboardRoute,
  RewardRoute: RewardRoute,
  HealthTalkIdRoute: HealthTalkIdRoute,
  PembekalanIdRoute: PembekalanIdRoute,
  HealthTalkIndexRoute: HealthTalkIndexRoute,
  PembekalanIndexRoute: PembekalanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
